// Seed data: merged step definitions + config defaults
// Used to auto-populate the StepDef table on first access

export interface StepSeed {
  number: number;
  title: string;
  shortTitle: string;
  description: string;
  dependsOn: number[];
  promptHint: string;
  customInstructions: string;
  outputFormat: string;
  outputDisplay: string;
  allowedTools: string[];
  maxTurns: number;
}

export const STEP_SEEDS: StepSeed[] = [
  {
    number: 1,
    title: "What is the task?",
    shortTitle: "The Task",
    description: "Define the core task at hand. What campaign, launch, or initiative are we setting direction for? What is the scope and what triggered this work?",
    dependsOn: [],
    promptHint: "Describe the task clearly. Include scope, triggers, and any constraints.",
    outputDisplay: "prose",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Define the campaign task clearly and concisely. Cover:\n- What is the specific initiative, launch, or campaign we are setting direction for?\n- What triggered this work?\n- What is the scope?\n- What is explicitly out of scope?\n- Who are the key stakeholders?",
    outputFormat: "Write a clear, structured narrative with these sections:\n## Initiative Overview\nA 2-3 sentence summary of the task.\n## Trigger & Background\nWhat prompted this work.\n## Scope\nWhat's included and what's not.\n## Stakeholders\nKey people and their roles.\n## Timeline\nKey dates and milestones if known.",
  },
  {
    number: 2,
    title: "Why was the product developed?",
    shortTitle: "Product Origin",
    description: "Understand the origin story. What market need, customer pain, or strategic vision led to this product or offering being created?",
    dependsOn: [1],
    promptHint: "Trace back to the original motivation. Why does this product exist?",
    outputDisplay: "prose",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Trace the origin story of the product or offering. Focus on:\n- What market need or customer pain led to its creation?\n- What was the founding insight?\n- How has the product evolved since its initial conception?\n- What strategic vision does it serve within the company's portfolio?",
    outputFormat: "Write a narrative covering:\n## The Market Gap\n## The Founding Insight\n## Evolution\n## Strategic Role",
  },
  {
    number: 3,
    title: "Why are we pushing the solution now?",
    shortTitle: "Timing & Urgency",
    description: "What makes this the right moment? Market shifts, regulatory changes, competitive pressure, internal readiness, or customer demand driving urgency.",
    dependsOn: [1, 2],
    promptHint: "Identify the timing triggers. What has changed that creates urgency?",
    outputDisplay: "bullet-cards",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Identify all timing drivers and urgency factors. Consider:\n- Market shifts\n- Regulatory changes\n- Competitive pressure\n- Internal readiness\n- Customer demand signals\n- External events",
    outputFormat: "Structure as a list of urgency drivers. For each driver use:\n### [Driver Name]\n**Type:** Market | Regulatory | Competitive | Internal | Customer | External\n**Urgency:** High | Medium | Low\n**Timeline:** When this becomes critical\n[2-3 sentence description]",
  },
  {
    number: 4,
    title: "What do we want to achieve?",
    shortTitle: "Goals",
    description: "Define concrete goals and success metrics. Revenue targets, market share, pipeline generation, awareness, or strategic positioning objectives.",
    dependsOn: [1, 3],
    promptHint: "Set measurable goals. Think revenue, pipeline, market share, awareness.",
    outputDisplay: "kpi-grid",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Define concrete, measurable objectives. For each objective:\n- State it clearly and specifically\n- Assign 1-2 KPIs with target values\n- Define the timeframe\n- Categorize as: Pipeline | Revenue | Awareness | Positioning | Engagement\n- Flag if the target is aspirational vs. data-backed",
    outputFormat: "Structure as a list of objectives. For each use:\n### [Objective Name]\n**Category:** Pipeline | Revenue | Awareness | Positioning | Engagement\n**KPI:** [Metric name]\n**Target:** [Specific number or range]\n**Timeframe:** [When]\n**Confidence:** High | Medium | Low\n[1-2 sentence description]",
  },
  {
    number: 5,
    title: "From a technical perspective, what does the product/offering do?",
    shortTitle: "Tech Capabilities",
    description: "Document the technical capabilities, features, and differentiators.",
    dependsOn: [1, 2],
    promptHint: "List concrete technical capabilities and differentiators.",
    outputDisplay: "bullet-cards",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Document every technical capability and differentiator. Be specific about what the product does technically, how it works differently from alternatives, performance characteristics, and integration points.",
    outputFormat: "Structure as capability cards. For each use:\n### [Capability Name]\n**Category:** Core | Differentiator | Integration | Performance\n**What it does:** [1 sentence]\n**How it works:** [2-3 sentences]\n**Why it matters:** [Business impact]\n**Differentiator:** [How this compares to alternatives]",
  },
  {
    number: 6,
    title: "Which business problems does this solve?",
    shortTitle: "Problems Solved",
    description: "Map technical capabilities to real business problems customers face.",
    dependsOn: [2, 5],
    promptHint: "For each business problem: describe the pain, its impact, and how the product solves it.",
    outputDisplay: "bullet-cards",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Map technical capabilities to real business problems. For each problem:\n- Describe the pain in the customer's language\n- Quantify the impact where possible\n- Explain how the product solves it\n- Note which segments feel this pain most acutely\n- Rate problem severity: Critical | Significant | Nice-to-have",
    outputFormat: "Structure as problem cards. For each use:\n### [Business Problem]\n**Severity:** Critical | Significant | Nice-to-have\n**Who feels it:** [Segments/roles]\n**The pain:** [Customer language, 2-3 sentences]\n**Impact:** [Quantified]\n**How we solve it:** [Specific capabilities]",
  },
  {
    number: 7,
    title: "In which business problems are other solutions more relevant?",
    shortTitle: "Not Our Fight",
    description: "Honestly assess where competing products or alternative approaches are better suited.",
    dependsOn: [5, 6],
    promptHint: "Be honest about limitations. Where do competitors or alternatives win?",
    outputDisplay: "bullet-cards",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Be honest and strategic about where this product is NOT the best fit. Cover at what scale/context other solutions are better, genuine limitations, and where sales should defer.",
    outputFormat: "Structure as boundary cards. For each use:\n### [Scenario Where We're Not Best Fit]\n**Better alternative:** [Solution]\n**Why:** [2-3 sentences]\n**Scale/Context:** [When this applies]\n**Recommendation:** [What sales/marketing should do]",
  },
  {
    number: 8,
    title: "What must be in place before you can use and benefit from the solution?",
    shortTitle: "Prerequisites",
    description: "Identify prerequisites, infrastructure, capabilities, or conditions needed for adoption.",
    dependsOn: [5, 6],
    promptHint: "List infrastructure, organizational, financial, and technical prerequisites.",
    outputDisplay: "bullet-cards",
    allowedTools: ["Read", "Glob", "Grep"],
    maxTurns: 10,
    customInstructions: "Identify everything that must be in place for a customer to adopt and benefit. Categories: Infrastructure, Organizational, Technical, Regulatory, Commercial.",
    outputFormat: "Structure as prerequisite cards. For each use:\n### [Prerequisite]\n**Category:** Infrastructure | Organizational | Technical | Regulatory | Commercial\n**Criticality:** Must-have | Should-have | Nice-to-have\n**Description:** [What needs to be in place]\n**Implication:** [What happens if not met]",
  },
  {
    number: 9,
    title: "Which segments have these business problems?",
    shortTitle: "Target Segments",
    description: "Identify and prioritize customer segments that experience the business problems identified.",
    dependsOn: [6, 7, 8],
    promptHint: "Identify segments by industry, company type, size. Assess urgency, fit, and readiness.",
    outputDisplay: "table",
    allowedTools: ["Read", "Glob", "Grep", "WebSearch", "WebFetch"],
    maxTurns: 15,
    customInstructions: "Identify and prioritize customer segments. For each segment assess problem urgency, solution fit, prerequisites readiness, segment size, and existing proof points.",
    outputFormat: "Present as a prioritized table:\n\n| Segment | Industry | Size Profile | Problem Urgency | Solution Fit | Prerequisites Met | Priority | Proof Points |\n|---------|----------|-------------|-----------------|-------------|-------------------|----------|-------------|\n\nAfter the table, add a brief paragraph for each Tier 1 segment.",
  },
  {
    number: 10,
    title: "In which geographies is the business problem most present/most urgent?",
    shortTitle: "Priority Geographies",
    description: "Map business problems to geographies by regulatory environment, market maturity, and competitive landscape.",
    dependsOn: [6, 9],
    promptHint: "Analyze geographies by regulatory drivers, market maturity, infrastructure, competition.",
    outputDisplay: "table",
    allowedTools: ["Read", "Glob", "Grep", "WebSearch", "WebFetch"],
    maxTurns: 15,
    customInstructions: "Map business problems to geographies. Assess each on: regulatory environment, market maturity, infrastructure readiness, competitive intensity, segment density, strategic fit.",
    outputFormat: "Present as a prioritized table:\n\n| Geography | Regulatory Driver | Market Maturity | Infra Readiness | Competition | Segment Density | Priority | Key Consideration |\n|-----------|------------------|-----------------|-----------------|-------------|-----------------|----------|-------------------|\n\nAfter the table, add a brief paragraph for each Tier 1 geography.",
  },
  {
    number: 11,
    title: "What are the economical potential for these segments in these geographies?",
    shortTitle: "Market Sizing",
    description: "Size the opportunity for prioritized segment-geography combinations.",
    dependsOn: [9, 10],
    promptHint: "For each segment x geography: estimate TAM, SAM, SOM. Include deal size and confidence.",
    outputDisplay: "table",
    allowedTools: ["Read", "Glob", "Grep", "WebSearch", "WebFetch"],
    maxTurns: 15,
    customInstructions: "Size the opportunity for each prioritized segment x geography combination. Include TAM, SAM, SOM, average deal size, sales cycle length, and confidence level. Flag where data is insufficient.",
    outputFormat: "Present as a market sizing table:\n\n| Segment | Geography | TAM | SAM | SOM (12-24mo) | Avg Deal Size | Cycle Length | Confidence | Data Source |\n|---------|-----------|-----|-----|---------------|---------------|--------------|------------|-------------|\n\nAfter the table, add notes on methodology and key assumptions.",
  },
  {
    number: 12,
    title: "What competing solutions are most likely targeting these segments?",
    shortTitle: "Competition",
    description: "Map the competitive landscape for prioritized segments and geographies.",
    dependsOn: [7, 9, 10],
    promptHint: "For each competitor: approach, strengths, weaknesses, positioning, pricing, traction.",
    outputDisplay: "table",
    allowedTools: ["Read", "Glob", "Grep", "WebSearch", "WebFetch"],
    maxTurns: 15,
    customInstructions: "Map the competitive landscape. For each competitor cover approach, positioning, strengths, weaknesses, geographic/segment focus, pricing model, market traction. Include both direct competitors and alternative approaches.",
    outputFormat: "Present as a competitor comparison table:\n\n| Competitor | Approach | Key Strength | Key Weakness | Geo Focus | Segment Focus | Pricing Model | Market Traction | Threat Level |\n|-----------|----------|-------------|-------------|-----------|---------------|---------------|-----------------|-------------|\n\nAfter the table, write a Competitive Positioning Summary.",
  },
  {
    number: 13,
    title: "Get to, by?",
    shortTitle: "Get To, By",
    description: "Synthesize everything into actionable \"Get [audience] to [action] by [method]\" direction statements.",
    dependsOn: [4, 9, 10, 11, 12],
    promptHint: "For each priority segment x geography: write a Get/To/By statement.",
    outputDisplay: "statement-cards",
    allowedTools: ["Read"],
    maxTurns: 10,
    customInstructions: "Synthesize all prior steps into actionable direction statements using the Get/To/By framework. Each statement should be specific enough to brief a creative team, grounded in prior step insights, and measurable against KPIs from Step 4.",
    outputFormat: "Structure as strategy statements. For each use:\n\n### [Segment] — [Geography]\n**Get** [who — specific audience]\n**To** [what — desired action or belief shift]\n**By** [how — channels, messages, tactics]\n\n**Priority:** Primary | Secondary\n**Linked KPIs:** [Which KPIs this drives]\n**Key Message Angle:** [Core message hook]\n**Primary Channels:** [Top 2-3 channels]",
  },
];
